### ISSUE TITLE
Removing all colums from tables

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#116]
Currently, it is possible to remove all the columns from the table views, which leads to the errors.
 
- Go to a table (Measurements, Samples…) and then to More-Change columns 
- Deselect all options (move them from the right field to the left)  and save

The error will occur when reopening the table:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 145, in change
    self.filterHeader = [i[1:] if i[0]=='-'   else i for i in self.filterHeader]  #change -something to something
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 145, in <listcomp>
    self.filterHeader = [i[1:] if i[0]=='-'   else i for i in self.filterHeader]  #change -something to something
IndexError: string index out of range
Not checked: 57(old)

If the same is done for the project list: 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 275, in <module>
    startMain()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 267, in startMain
    app, window = mainGUI()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 228, in mainGUI
    main_window = MainWindow()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 96, in __init__
    self.sidebar = Sidebar(self.comm)  # sidebar with buttons
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/sidebar.py", line 44, in __init__
    self.change()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/sidebar.py", line 76, in change
    projName = project['value'][0]
IndexError: list index out of range

As a fix, one can restrict the users from removing all table columns by making the "name" a mandatory one.

**Comment by HTsybenko** [comment]
For now, this issue still can be recreated, both for projects table as well as for the other tables.

**Comment by SteffenBrinckmann** [comment]
True, for some unexplainable reason, I removed (2023-10-23) the fix that I had implemented before.
