### ISSUE TITLE
Jpeg extractor issue

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#118]
The following error occurs when importing a jpeg image (uploaded to [Sciebo](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu?path=%2FIssue_118))

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 64, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/sidebar.py", line 176, in execute
    self.comm.backend.scanProject(self.progress, self.openProjectId, '')
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 412, in scanProject
    self.addData('-', {'-name':path}, hierStack)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 274, in addData
    if self.cwd is not None and doc['-type'][0][0]=='x':
TypeError: 'NoneType' object is not subscriptable

**Comment by SteffenBrinckmann** [comment]
Is a Pasta problem that is triggerd by an extractor, but as written in the last line
"File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 274, in addData"
the cause is something in pasta
