### ISSUE TITLE
Import and edit the eLabFTW project

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#133]
- Import any eLabFTW project (for instance, single-experiment.eln file). 

- Open it in project view and go to edit project.

Following error occurs:

![Screenshot from 2023-11-10 16-46-19](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/4a78f3b8-3570-4755-be18-efc15c20ef63)

Also, autosave errors are raised:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 209, in autosave
    elif isinstance(getattr(self, f'key_{key}'), QLineEdit):
AttributeError: 'Form' object has no attribute 'key_from eLabFTW'

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 201, in autosave
    def autosave(self) -> None:
KeyboardInterrupt

**Comment by HTsybenko** [comment]
The error reported in the initial issue does not occur anymore. Other errors related to importing eLabFTW projects will be reported in the separate issue.
