### ISSUE TITLE
Adding new columns to the tables

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#145]
In the table view, go to More-edit columns. 
In the empty field on the bottom left of the editing window, add text (for instance, "metaVendor/fileExtension"), move to the right side and save. 

**ERROR dsv01: something unexpected has happened.
**ERROR dgv01: Database / Network problem for path | viewDocType/x0
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 547, in getView
    res = list(v.result)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/result.py", line 361, in __iter__
    response = self._call(**{k: v
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/view.py", line 236, in __call__
    resp = get_docs(self._r_session,
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/_common_util.py", line 268, in get_docs
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found deleted for url: http://127.0.0.1:5984/research/_design/viewDocType/_view/x0?limit=101

**ERROR dgv01: Database / Network problem for path | viewDocType/x0All
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 547, in getView
    res = list(v.result)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/result.py", line 361, in __iter__
    response = self._call(**{k: v
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/view.py", line 236, in __call__
    resp = get_docs(self._r_session,
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/_common_util.py", line 268, in get_docs
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found deleted for url: http://127.0.0.1:5984/research/_design/viewDocType/_view/x0All?limit=101

**ERROR dgv01: Database / Network problem for path | viewDocType/x0
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 547, in getView
    res = list(v.result)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/result.py", line 361, in __iter__
    response = self._call(**{k: v
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/view.py", line 236, in __call__
    resp = get_docs(self._r_session,
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/_common_util.py", line 268, in get_docs
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found deleted for url: http://127.0.0.1:5984/research/_design/viewDocType/_view/x0?limit=101

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 147, in change
    self.filterHeader = self.comm.backend.db.getColumnNames()[self.docType].split(',')
KeyError: 'x0'
**ERROR dgv01: Database / Network problem for path | viewDocType/x0
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 547, in getView
    res = list(v.result)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/result.py", line 361, in __iter__
    response = self._call(**{k: v
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/view.py", line 236, in __call__
    resp = get_docs(self._r_session,
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/_common_util.py", line 268, in get_docs
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found deleted for url: http://127.0.0.1:5984/research/_design/viewDocType/_view/x0?limit=101

**ERROR dgv01: Database / Network problem for path | viewDocType/x0
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 547, in getView
    res = list(v.result)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/result.py", line 361, in __iter__
    response = self._call(**{k: v
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/view.py", line 236, in __call__
    resp = get_docs(self._r_session,
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/_common_util.py", line 268, in get_docs
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found deleted for url: http://127.0.0.1:5984/research/_design/viewDocType/_view/x0?limit=101

**Comment by SteffenBrinckmann** [comment]
@HTsybenko I tried it with tables for measurements, samples and projects: and in all cases, I could not reproduce your bug. I guess, it must be related to a version issue (you use a different version than I) Can you check if this issue still exists in the next release?
