### ISSUE TITLE
Deleting projects with same names

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#162]
1) Import a project from the .eln file
2) Delete the project via GUI
3) Import the same project from the .eln file
4) Delete the project via GUI

or 

1) Create a project
2) Delete the project via GUI
3) Create a project with the same name
4) Delete the project via GUI

Since the trash_project folder was already created before the last testing step, PASTA responds with the following error message:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 203, in execute
    oldPath.rename(newPath)
  File "/usr/lib/python3.10/pathlib.py", line 1234, in rename
    self._accessor.rename(self, target)
OSError: [Errno 39] Directory not empty: '/home/htsybenko/Data/UnidentifiedStuff' -> '/home/htsybenko/Data/trash_UnidentifiedStuff'

**Comment by HTsybenko** [comment]
In 2.4.26, the error does not occur anymore.

Instead, a warning message appears: "Old project data exists. Do you want to delete?"
The warning message sounds a bit confusing.
"Old project data exists" does not specify what data is meant (e.g., in the previously deleted project with the same name). 
"Do you want to delete?" does not mention which data will be deleted (e.g., the data in the folder will be overwritten with the newly deleted data).

Overall, I think that a better way to resolve this issue and not lose data would be the same as when the user creates multiple items with the same name: check if the folder with the same name exists in the working directory; if yes, add an incremented number at the end.

**Comment by HTsybenko** [comment]
In addition, If the user answers with "No" to the "Old project data exists. Do you want to delete?", the error occurs again:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 210, in execute
    oldPath.rename(newPath)
  File "/usr/lib/python3.10/pathlib.py", line 1234, in rename
    self._accessor.rename(self, target)
OSError: [Errno 39] Directory not empty: '/home/htsybenko/Data/NewProject' -> '/home/htsybenko/Data/trash_NewProject'
 
The project is then deleted without a possibility to restore it from trash_project folder (old data is still there). 

Also, the project does not disappear from the left side bar, until any of the table views is opened. 
Upon clicking on it, it responds with an error:
home/htsybenko/Data/trash_NewProject'
**ERROR getHierarchy Did not find corresponding level=1 under docID x-abfbaf33da8b445cbfe4d86a556bfd34
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 164, in change
    self.projHeader()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 54, in projHeader
    if [b for b in self.docProj['-branch'] if False in b['show']] else \
KeyError: '-branch'

Verify DB has following responses:
dch11: image not in measurement m-fe95b05e426a43479ba966b687aa2251
dch07: branch not in parent with id x-abfbaf33da8b445cbfe4d86a556bfd34
