### ISSUE TITLE
Opening PASTA-ELN after a fresh installation

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#163]
1) The user installed PASTA-ELN according to the guide. No issues occurred during the installation.
2) Tried starting the software for the first time.

Error message:

Traceback (most recent call last):
  File "/home/xli/pasta-folder/bin/pastaELN", line 5, in <module>
    from pasta_eln.gui import main
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/gui.py", line 17, in <module>
    from .GUI.body import Body
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/GUI/body.py", line 4, in <module>
    from .docTypes import DocTypes
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/GUI/docTypes.py", line 4, in <module>
    from .table import Table
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/GUI/table.py", line 10, in <module>
    from .tableHeader import TableHeader
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/GUI/tableHeader.py", line 5, in <module>
    from ..guiStyle import IconButton, widgetAndLayout, showMessage
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/guiStyle.py", line 10, in <module>
    from .backend import Backend
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/backend.py", line 8, in <module>
    from .mixin_cli import CLI_Mixin
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/mixin_cli.py", line 3, in <module>
    from .miscTools import createDirName
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/miscTools.py", line 8, in <module>
    from .handleDictionaries import dict2ul
  File "/home/xli/pasta-folder/lib/python3.8/site-packages/pasta_eln/handleDictionaries.py", line 6, in <module>
    def ontology2Labels(ontology:dict[str,Any], tableFormat:dict[str,Any]) -> dict[str,Any]:
TypeError: 'type' object is not subscriptable

**Comment by SteffenBrinckmann** [comment]
@HTsybenko Can you please check the python version "python --version"? I suspect this is an old python version.

**Comment by HTsybenko** [comment]
@SteffenBrinckmann The default Python version that was installed on that computer was 3.8.10. (Ubuntu 20.04.6) so you are correct.
