### ISSUE TITLE
CouchDB connectivity issues in pasta_eln-2.4.27

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#201]
1) When configuring a freshly installed PASTA-ELN version available by default (pasta_eln-2.4.27), there is an error during installation of CouchDB:

(![image](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/28e863b7-83bb-4421-bd1a-36e42b34a847)

After that, a following error occurs in the terminal:

**ERROR dit01: Could not connect with username+password to local server
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 64, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/configSetupLinux.py", line 131, in execute
    exampleData(True, self.callbackProgress)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/installationTools.py", line 329, in exampleData
    backend.exit(deleteDB=True)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 97, in exit
    self.db.exit(deleteDB)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 199, in exit
    self.db.client.delete_database(self.databaseName)
AttributeError: 'Database' object has no attribute 'db'
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 129, in change
    self.data = self.comm.backend.db.getView(path)
AttributeError: 'Backend' object has no attribute 'db'

2) For the most recent beta version (pasta_eln-2.5.0b3), CouchDB installs without any issues.

**Comment by HTsybenko** [comment]
The issue is fixed in pasta_eln-2.4.28.
