### ISSUE TITLE
"Hide project details" results in error

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#202]
The issue is the same as #161, which was fixed a while ago but has occurred again.
Pasta version pasta_eln-2.5.0b3

To reproduce:

1. Open project view
2. Go to "Visibility" options
3. Select "Hide project details"

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 125, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 243, in execute
    if self.infoW is not None and self.infoW.isHidden():
AttributeError: 'Project' object has no attribute 'infoW'. Did you mean: 'infoW_'?

**Comment by HTsybenko** [comment]
In pasta_eln-2.5.0b5, "Hide project details" functions correctly and does not cause errors.
