### ISSUE TITLE
Imported eln files incorrectly displayed

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#204]
Pasta version pasta_eln-2.5.0b3

1. Create a project. 
2. Open it and export as an eln file.
3. Delete it from PASTA-ELN.
4. Import the eln file.
5. Click on it to open project view.

The project will not be displayed correctly.

![Screenshot from 2024-03-04 12-05-23](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/fa8fc550-4b25-474c-83c3-730daec86232)

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 161, in change
    self.projHeader()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 110, in projHeader
    self.commentTE.setMarkdown(markdownStyler(self.docProj['comment']))
KeyError: 'comment'

**Comment by HTsybenko** [comment]
In 2.5.0b5, the imported eln projects are displayed correctly.
