### ISSUE TITLE
Rerunning extractors of items with no files

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#206]
Pasta version pasta_eln-2.5.0b3

Rerunning extractors of items with no attached files results in the error and stops the rerunning process for all files:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 125, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 332, in execute
    if doc['-branch'][0]['path'].startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by HTsybenko** [comment]
The issue is fixed in 2.5.0b5.
