### ISSUE TITLE
Saving the "Author" Configuration

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#221]
Go to the Authors in configuration, click save (with or without editing).

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 58, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/configAuthors.py", line 117, in execute
    fConf.write(json.dumps(self.configuration,indent=2))
AttributeError: 'ConfigurationAuthors' object has no attribute 'configuration'

**Comment by SteffenBrinckmann** [comment]
similar as #222, fixed together

**Comment by SteffenBrinckmann** [comment]
fixed in 2.5.0b6
