### ISSUE TITLE
Issues during the corrosion data import

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#232]
After executing the "python -m pasta_eln.serverActions" command and following all steps, a following error occurs:

[1] couchDB_backup_127001_20240316T140124.zip
Which file to use for restored? (1-1) 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 582, in <module>
    main()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 559, in main
    restoreCouchDB()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 456, in restoreCouchDB
    docID = fileParts[1]
IndexError: list index out of range

**Comment by HTsybenko** [comment]
In 2.5.1b1, this error occurs:

[1] couchDB_backup_127001_20240316T140124.zip
Which file to use for restored? (1-1) 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 586, in <module>
    main()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 563, in main
    restoreCouchDB()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 458, in restoreCouchDB
    docID = fileParts[1]
IndexError: list index out of range

**Comment by SteffenBrinckmann** [comment]
This is fixed in version 2.5.1 already, but wait for HT to verify

**Comment by HTsybenko** [comment]
The corrosion data can be imported after the fix.

However, the import ends with the following error again:

...
Saved document: research m-9c4cb5bb637049f49aab6b4_00860234
Saved document: research m-9c4cb5bb637049f49aab6b4_00010707
Saved document: research m-9c4cb5bb637049f49aab6b4_00530014
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 589, in <module>
    main()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 566, in main
    restoreCouchDB()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/serverActions.py", line 492, in restoreCouchDB
    docID = fileParts[1]
IndexError: list index out of range

**Comment by SteffenBrinckmann** [comment]
@HTsybenko When you test it in the next beta-release, can you send me the output in the terminal. It should not produce the IndexError and I created a safeguard for it. But I would like to know the offending file, and that should  be printed.

**Comment by HTsybenko** [comment]
I guess, this is the file, you were referring to:

**ERROR-Attachment: Cannot process file couchDB_backup_127001_20240316T140124/: does not have 1+2 parts
**ERROR-Attachment: Cannot process file couchDB_backup_127001_20240316T140124/research/: does not have 1+2 parts
**ERROR-Attachment: Cannot process file couchDB_backup_127001_20240316T140124/research/_design/: does not have 1+2 parts
**ERROR-Attachment: Cannot process file couchDB_backup_127001_20240316T140124/research/_design/viewHierarchy: does not have 1+2 parts
**ERROR-Attachment: Cannot process file couchDB_backup_127001_20240316T140124/research/_design/viewIdentify: does not have 1+2 parts
**ERROR-Attachment: Cannot process file couchDB_backup_127001_20240316T140124/research/_design/viewDocType: does not have 1+2 parts
