### ISSUE TITLE
Data hierarchy editor allows to remove default metadata group

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#235]
- Go to data hierarchy editor.
- For any data type, delete its default metadata group and save.
- Pasta will restart.
- Try to edit an item of the edited data type.

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 132, in formDoc
    formWindow = Form(self.comm, doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 78, in __init__
    dataHierarchyNode['default'].append({'name':keyInDocNotHierarchy})
KeyError: 'default'

The default metadata group should not be removable.

**Comment by SteffenBrinckmann** [comment]
Redesign will take care of this
