### ISSUE TITLE
Cryptography module not found 

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#290]
When starting pasta_eln-2.5.3b1, a following error occurs:

(envir) htsybenko@iek2123:~$ pastaELN
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 17, in <module>
    from pasta_eln.GUI.dataverse.config_dialog import ConfigDialog
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/dataverse/config_dialog.py", line 25, in <module>
    from pasta_eln.dataverse.database_api import DatabaseAPI
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/dataverse/database_api.py", line 19, in <module>
    from pasta_eln.dataverse.base_database_api import BaseDatabaseAPI
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/dataverse/base_database_api.py", line 22, in <module>
    from pasta_eln.dataverse.utils import log_and_create_error, read_pasta_config_file
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/dataverse/utils.py", line 24, in <module>
    from cryptography.fernet import Fernet, InvalidToken
ModuleNotFoundError: No module named 'cryptography'

Installing the missing module gives:
(envir) htsybenko@iek2123:~$ pip install cryptography
Requirement already satisfied: cryptography in ./Temp/envir/lib/python3.10/site-packages (40.0.2)
Requirement already satisfied: cffi>=1.12 in ./Temp/envir/lib/python3.10/site-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in ./Temp/envir/lib/python3.10/site-packages (from cffi>=1.12->cryptography) (2.21)

**Comment by HTsybenko** [comment]
Fixes by manual uninstalling and reinstalling the package, but strange that it occurs anyway.

**Comment by SteffenBrinckmann** [comment]
I forgot to adopt the requriments file
