### ISSUE TITLE
Opening "Dataverse Configuration" throws errors

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#292]
1. Install PASTA or do the System - Configuration - Setup - Start Analyze and repair sequence.

2. Go to System - Dataverse Configuration.

A following error would occur in the terminal:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 127, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 185, in execute
    self.dataverseConfig = ConfigDialog()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/dataverse/config_dialog.py", line 93, in __init__
    self.config_model = self.db_api.get_config_model() or ConfigModel()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/dataverse/database_api.py", line 247, in get_config_model
    config_model = self.get_model(self.config_doc_id, ConfigModel)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/dataverse/database_api.py", line 230, in get_model
    return model_type(**self.db_api.get_document(model_id))
TypeError: pasta_eln.dataverse.config_model.ConfigModel() argument after ** must be a mapping, not NoneType

3. If the user goes instead to System - Upload to Dataverse, the configuration menu would open, and the System - Dataverse Configuration sequence would also response as expected without errors.

**Comment by jmurugan-fzj** [comment]
@HTsybenko This is been fixed already in the recent version, please re-check this issue again, Thanks

**Comment by HTsybenko** [comment]
@jmurugan-fzj In version 2.5.3b1, which is currently available for testing, the issue is still reproducible. 
The regular installation, however, installs version 2.5.2, where the Dataverse feature is not yet present.

**Comment by jmurugan-fzj** [comment]
@HTsybenko Wait until the next version or the latest version with the feature is ready and then you could start the testing, I meant about the latest committed version in the main branch..!

**Comment by HTsybenko** [comment]
The issue is fixed in 2.6.0b1.
