### ISSUE TITLE
Error during eln file export when the organization list is empty

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#294]
1) Go to the Configuration and remove default organization via "-"
2) Try to export any project as an eln file:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 127, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 147, in execute
    status = exportELN(self.comm.backend, [self.comm.projectID], fileName, docTypes)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 503, in exportELN
    'affiliation': [{'organization': authors[0]['organizations'][0]['organization'],
IndexError: list index out of range

**Comment by HTsybenko** [comment]
Fixed in 2.6.0b1.
