### ISSUE TITLE
Importing eln file 2

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#296]
1) Export PastasExampleProject as an eln file
2) System - Configuration - Setup - Start. Do not create a new example project.
3) Import the eln file

Process: ./test2/PastasExampleProject/

Process: ./test2/PastasExampleProject/000_ThisIsAnExampleTask/

Process: ./test2/PastasExampleProject/001_ThisIsAnotherExampleTask/

Process: ./test2/PastasExampleProject/001_ThisIsAnotherExampleTask/000_ThisIsAnExampleSubtask/

Process: ./test2/PastasExampleProject/001_ThisIsAnotherExampleTask/001_ThisIsAnotherExampleSubtask/

Process: ./test2/PastasExampleProject/002_DataFiles/

Process: https:/upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Misc_pollen.jpg/315px-Misc_pollen.jpg
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 127, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 159, in execute
    status = importELN(self.comm.backend, fileName)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 301, in importELN
    addedDocuments += processPart(part)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 291, in processPart
    addedDocs += processPart(child)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 291, in processPart
    addedDocs += processPart(child)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 255, in processPart
    backend.useExtractors(Path(elnID), doc['shasum'], doc)
KeyError: 'shasum'

**Comment by SteffenBrinckmann** [comment]
same as #229
