### ISSUE TITLE
Importing sleepy brain data for the workshop

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#31]
When scanning a directory and processing the [sub-9001_ses-2_task-hands_physio.tsv.gz](https://openneuro.org/datasets/ds000201/versions/1.0.3/file-display/sub-9001:ses-2:func:sub-9001_ses-2_task-hands_physio.tsv.gz), the progress bar stops updating and scanning stops with an error:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 68, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/sidebar.py", line 173, in execute
    self.comm.backend.scanProject(self.progress, self.openProjectId, '')
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 442, in scanProject
    self.scanProject(progressBar, projID, projPath)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 442, in scanProject
    self.scanProject(progressBar, projID, projPath)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 442, in scanProject
    self.scanProject(progressBar, projID, projPath)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 412, in scanProject
    self.addData('-', {'-name':path}, hierStack)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 241, in addData
    self.useExtractors(path,shasum,doc)  #create image/content
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 485, in useExtractors
    for item in doc[meta]:
KeyError: 'metaVendor'

log:
09-12 13:17:27|INFO:Start PASTA GUI
09-12 13:17:30|DEBUG:gui:formdoc of type ['x0']
09-12 13:17:32|DEBUG:Add/edit data in cwd:/home/htsybenko/Data with stack:[] and name: Test type:['x0'] and edit: False
09-12 13:17:32|DEBUG:successfully saved doc with type and branch x-783d05f5e9f64d4aa0a1517c920795ee x0  |  [{'stack': [], 'child': 0, 'path': 'Test', 'show': [True]}]

09-12 13:17:45|DEBUG:project:changeProject |x-783d05f5e9f64d4aa0a1517c920795ee||
09-12 13:17:45|INFO:Scan: add file to DB: Test/sub-9001_ses-2_task-hands_physio.tsv.gz
09-12 13:17:45|DEBUG:Add/edit data in cwd:Test with stack:['x-783d05f5e9f64d4aa0a1517c920795ee'] and name: Test/sub-9001_ses-2_task-hands_physio.tsv.gz type:['-'] and edit: False

**Comment by SteffenBrinckmann** [comment]
since it is a metaVendor keyError in useExtractors:
- the extractor was not correct, I hope I repaired it
- a safeguard against crashes was implemented as part of #40

**Comment by HTsybenko** [comment]
I have replaced the old extractor with a new one [iek2_extractors](https://jugit.fz-juelich.de/iek-2/extractors/-/blob/main/extractor_gz.py?ref_type=heads).

The .tsv.gz files were imported into the PastasExampleProject as unidentified with the following report on extractor test:

check file: /home/htsybenko/Data/PastasExampleProject/sub-9001_ses-1_task-hands_physio.tsv.gz
use extractor: /home/htsybenko/iek2_software/extractors/extractor_gz.py
Python error in extractor
Please visit [website](https://pasta-eln.github.io/pasta-eln/extractors.html#python-error)
Traceback (most recent call last):
File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/nibabel/loadsave.py", line 100, in load
stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sub-9001_ses-1_task-hands_bold.nii.gz'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 563, in testExtractor
module = importlib.import_module(pyFile[:-3])
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
FileNotFoundError: No such file or no access: 'sub-9001_ses-1_task-hands_bold.nii.gz'

Since the files were imported without breaking the scanning process, this issue can be still assumed as resolved.
