### ISSUE TITLE
PASTA SQLite

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#328]
@SteffenBrinckmann 
**1. Installation terminal output (except the installed packages) :**
(pasta_3_10) htsybenko@iek2123:~$ pip install git+https://github.com/PASTA-ELN/pasta-eln@sb_sqlite
Collecting git+https://github.com/PASTA-ELN/pasta-eln@sb_sqlite
  Cloning https://github.com/PASTA-ELN/pasta-eln (to revision sb_sqlite) to /tmp/pip-req-build-eqy9c1nj
  Running command git clone --filter=blob:none --quiet https://github.com/PASTA-ELN/pasta-eln /tmp/pip-req-build-eqy9c1nj
  Running command git checkout -b sb_sqlite --track origin/sb_sqlite
  Switched to a new branch 'sb_sqlite'
  Branch 'sb_sqlite' set up to track remote branch 'sb_sqlite' from 'origin'.
  Resolved https://github.com/PASTA-ELN/pasta-eln to commit 9cee58e9d70796bbee8698e29e45f311845be969
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
....
Building wheels for collected packages: pasta_eln
  Building wheel for pasta_eln (pyproject.toml) ... done
  Created wheel for pasta_eln: filename=pasta_eln-2.6.0b3-py3-none-any.whl size=357658 sha256=feb20671496137a04f823dfef0b2bea385b687f6c02a75644edc0332132d455d
  Stored in directory: /tmp/pip-ephem-wheel-cache-_dxh50h_/wheels/6a/34/c3/e9a258c2802ca8a859f2cf7497ff2f623b49a9ae98586b2e03
Successfully built pasta_eln
Installing collected packages: pasta_eln
Successfully installed pasta_eln-2.6.0b3

**2. Starting via python3.10 -m pasta_eln.gui**

**2.1. If the "Data" folder including pastaELN.db are not present (were deleted before the installation):** 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/gui.py", line 293, in <module>
    startMain()
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/gui.py", line 285, in startMain
    app, window = mainGUI()
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/gui.py", line 243, in mainGUI
    main_window = MainWindow()
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/gui.py", line 47, in __init__
    self.backend = Backend()
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/backend.py", line 34, in __init__
    self.initialize(defaultProjectGroup, **kwargs)
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/backend.py", line 74, in initialize
    self.db = SqlLiteDB(self.configuration, basePath=self.basePath)
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/sqlite.py", line 60, in __init__
    self.connection = sqlite3.connect(basePath/"pastaELN.db")
sqlite3.OperationalError: unable to open database file

**2.2. If the "Data" folder including pastaELN.db are present:** 
- opens immediately
- no "Start analyze and repair"
- no "working directory" selection
![Screenshot from 2024-07-30 08-43-41](https://github.com/user-attachments/assets/2388a11d-ccbb-42bd-b410-a4289c6ef8ea)

Trying to add a new project:
Traceback (most recent call last):
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/gui.py", line 129, in formDoc
    formWindow = Form(self.comm, doc)
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 135, in __init__
    self.updateTagsBar()
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 570, in updateTagsBar
    for tag in self.doc['tags']:
KeyError: 'tags'

Trying to add a subfolder in PastasExampleProject:
Traceback (most recent call last):
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 60, in <lambda>
    self.clicked.connect(lambda: widget.execute(command))                                                    # type: ignore[attr-defined]
  File "/home/htsybenko/pasta_3_10/lib/python3.10/site-packages/pasta_eln/GUI/project.py", line 303, in execute
    title = self.comm.backend.db.dataHierarchy['x1']['title'].lower()[:-1]
TypeError: 'method' object is not subscriptable

**3. Installation in a new venv**
The "cloudant" module is absent after installation, and should be added to requirements.

**Comment by SteffenBrinckmann** [comment]
@HTsybenko did you delete the configuration file pastaEln_v3 before you started?

**Comment by HTsybenko** [comment]
@SteffenBrinckmann 
I did not delete the mentioned configuration file.
Before the installation, "rm .pastaELN.json pastaELN.log" is always executed. 

Afterwards, I tested the installation and launching with and without the "Data" folder removal.

**Comment by SteffenBrinckmann** [comment]
Not observed anymore
