### ISSUE TITLE
Importing the eLabFTW .eln files

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#37]
Importing the eLabFTW [multiple-experiments.eln](https://github.com/TheELNConsortium/TheELNFileFormat/blob/master/examples/elabftw/multiple-experiments.eln) or [single-experiment.eln](https://github.com/TheELNConsortium/TheELNFileFormat/blob/master/examples/elabftw/single-experiment.eln) file results in the following error:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 135, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 135, in execute
    status = importELN(self.comm.backend, fileName)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 225, in importELN
    addedDocuments += processPart(part)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 215, in processPart
    addedDocs += processPart(child)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/inputOutput.py", line 205, in processPart
    docID = backend.addData(docType, doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 241, in addData
    self.useExtractors(path,shasum,doc)  #create image/content
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/backend.py", line 485, in useExtractors
    for item in doc[meta]:e
KeyError: 'metaVendor'

**Comment by SteffenBrinckmann** [comment]
Should be repaired by #60

**Comment by SteffenBrinckmann** [comment]
@HTsybenko can you check in the next version?

**Comment by HTsybenko** [comment]
In the latest version, no errors occur when importing the eln files from eLabFTW.
