### ISSUE TITLE
Table view: Change columns

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#59]
Clicking on “More- Change columns” in the table view leads to the error:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 279, in execute
    dialog = TableHeader(self.comm, self.docType)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/tableHeader.py", line 24, in __init__
    self.allSet = {i['name'] for group in self.db.ontology[docType]['prop']
AttributeError: 'TableHeader' object has no attribute 'db'

**Comment by SteffenBrinckmann** [comment]
repaired in pull request #72

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann During the verification of this issue, I have seen some other problem, not sure if this is related, please see this video for more info: [issues_after_change_columns_for_tables](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu?path=%2FIssue_59#/files_mediaviewer/issues_after_change_columns_for_tables.webm)

@HTsybenko I am not sure if you have already logged similar issues, if yes these problems can be fixed later!

**Comment by HTsybenko** [comment]
@jmurugan-fzj I suggest you report this problem in the video as a separate issue. It will be easier to handle it then.

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann @HTsybenko I had created a separate bug for the issue commented above: Filtering the tables using column names throws errors #76

**Comment by HTsybenko** [comment]
In the latest version, I could still reproduce the issue #59 with the error:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/table.py", line 280, in execute
    dialog = TableHeader(self.comm, self.docType)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/tableHeader.py", line 24, in __init__
    self.allSet = {i['name'] for group in self.db.ontology[docType]['prop']
AttributeError: 'TableHeader' object has no attribute 'db'
