### ISSUE TITLE
Hide in item editor

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#63]
In the project view or table view, open any item with an image to edit (for example - simple.png).
Right click on the enlarged image and click on “Hide”.

At this point, the terminal responds with an error:
 
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 362, in execute
    if executeContextMenu(self, command):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/_contextMenu.py", line 72, in executeContextMenu
    widget.comm.backend.db.hideShow(widget.docID)
AttributeError: 'Form' object has no attribute 'docID'

Log:
09-28 13:59:07|INFO:Start PASTA GUI
09-28 13:59:07|INFO:End PASTA GUI
09-28 13:59:09|DEBUG:project:changeProject |x-87d9dc4eefc544d8a144443653fab1be||
09-28 13:59:11|DEBUG:gui:formdoc m-5c4d60618fb1445f98fd1ee92fd348be

**Comment by HTsybenko** [comment]
The issue can be still recreated after the update.

Error message:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/guiStyle.py", line 131, in <lambda>
    self.triggered.connect(lambda : widget.execute(command))
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 362, in execute
    if executeContextMenu(self, command):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/_contextMenu.py", line 72, in executeContextMenu
    widget.comm.backend.db.hideShow(widget.docID)
AttributeError: 'Form' object has no attribute 'docID'

Log:
10-06 13:30:46|INFO:Start PASTA GUI
10-06 13:30:46|INFO:End PASTA GUI
10-06 13:30:47|DEBUG:project:changeProject |x-80d5bb8c7767474eada02e021dcc3787||
10-06 13:30:51|DEBUG:gui:formdoc m-4a48e38a448349cbaf4037b38eface80
10-06 13:30:54|DEBUG:Change project: docID -old- -new- m-4a48e38a448349cbaf4037b38eface80|['x-80d5bb8c7767474eada02e021dcc3787', 'x-eef5ce83a91c48c289de39fff7f17571']  0|['x-80d5bb8c7767474eada02e021dcc3787', 'x-eef5ce83a91c48c289de39fff7f17571'] 0 PastasExampleProject/002_DataFiles/000_simple.png
10-06 13:30:54|DEBUG:success BRANCH updated with type and branch m-4a48e38a448349cbaf4037b38eface80 measurement/image  |  [{'stack': ['x-80d5bb8c7767474eada02e021dcc3787', 'x-eef5ce83a91c48c289de39fff7f17571'], 'child': 0, 'path': 'PastasExampleProject/002_DataFiles/000_simple.png', 'show': [True, True, True]}]

**Comment by SteffenBrinckmann** [comment]
Yes,  it is not in the official release

**Comment by HTsybenko** [comment]
Hiding the item in the editing window does not lead to errors now, and hiding is executed correctly.
