### ISSUE TITLE
Deleting Structure 0 data types in Questionnaires

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#68]
The current version of Questionnaires allows deleting the data types of top structure levels (Structure 0) and save. 
It would be better to not allow saving the Questionnaire after such action.

After the deletion, the terminal responds with:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/.local/lib/python3.10/site-packages/pasta_eln/gui.py", line 11, in <module>
    from PySide6.QtCore import Qt, Slot, QCoreApplication  # pylint: disable=no-name-in-module
ImportError: libshiboken6.abi3.so.6.5: cannot open shared object file: No such file or directory

Reopening Pasta after Structure 0 deletion:

**ERROR dgv01: Database / Network problem for path | viewDocType/x0
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/database.py", line 542, in getView
    res = list(v.result)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/result.py", line 361, in __iter__
    response = self._call(**{k: v
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/view.py", line 236, in __call__
    resp = get_docs(self._r_session,
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/cloudant/_common_util.py", line 268, in get_docs
    resp.raise_for_status()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Object Not Found not_found missing_named_view for url: http://127.0.0.1:5984/research/_design/viewDocType/_view/x0?limit=101

**Comment by jmurugan-fzj** [comment]
@SteffenBrinckmann Should we restrict the users from deleting the structural types via ontology tool? Or should the pasta app be made robust to handle such cases also? What would be your suggestion?

**Comment by SteffenBrinckmann** [comment]
Good question. For pasta to work, only one layer (x0) is required. Hence, one has to remain.
