### ISSUE TITLE
Changing column names in table

### ISSUE THREAD

**Issue by jmurugan-fzj** [PASTA-ELN/pasta-eln#76]
- Open pasta App
- Go to Lists | Projects
- On the right top corner of the app, select More | Change Columns
- Select all the columns available on the left panel to the right and click "Save" to close the "Select table headers" dialog
- Immediately the project list go blank and also the sidebar
- Open More | Change Columns and deselect all the columns, press save button and this leads to Pasta app crash

See video for more info: [issues_after_change_columns_for_tables](https://fz-juelich.sciebo.de/s/vWTvyh4slWePAAu?path=%2FIssue_59#/files_mediaviewer/issues_after_change_columns_for_tables.webm)

**Comment by HTsybenko** [comment]
The issue can be still reproduced. 
After going through all the steps in the original report, PASTA crashes with the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 271, in <module>
    startMain()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 263, in startMain
    app, window = mainGUI()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 224, in mainGUI
    main_window = MainWindow()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 96, in __init__
    self.sidebar = Sidebar(self.comm)  # sidebar with buttons
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/sidebar.py", line 44, in __init__
    self.change()
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/sidebar.py", line 76, in change
    projName = project['value'][0]
IndexError: list index out of range

**Comment by SteffenBrinckmann** [comment]
If image is not present, but user selects it, it crashes

**Comment by HTsybenko** [comment]
There are no errors anymore when all the columns available on the left panel are moved to the right in the table editing window.

Other issues related to "Change columns" feature will be reported separately.
