### ISSUE TITLE
Editing unassigned items

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#82]
1. Go to any table view (Measurements, Samples, etc.).
2. Create an item via "Add". Keep the Project field "-unassigned-" and save.
3. Select the created item by checking its checkbox.
4. Go to "Selection" and click "Sequential edit". 

This will raise an error:
Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 127, in formDoc
    formWindow = Form(self.comm, doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 156, in __init__
    if '-branch' not in self.doc or all(line['id']!=branch['stack'][0] for branch in self.doc['-branch']):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 156, in <genexpr>
    if '-branch' not in self.doc or all(line['id']!=branch['stack'][0] for branch in self.doc['-branch']):
IndexError: list index out of range

Log:
10-10 12:59:43|INFO:Start PASTA GUI
10-10 12:59:43|INFO:End PASTA GUI
10-10 12:59:45|DEBUG:table:changeTable |measurement||
10-10 12:59:47|DEBUG:gui:formdoc of type ['measurement']
10-10 12:59:55|DEBUG:Add/edit data in cwd:/home/htsybenko/Data with stack:[] and name: Test_Item type:['measurement'] and edit: False
10-10 12:59:55|DEBUG:successfully saved doc with type and branch m-30f3c8ffd9ca429ab6726a4b317605f7 measurement  |  [{'stack': [], 'child': 9999, 'path': None, 'show': [True]}]

10-10 12:59:57|DEBUG:details:changeDetails |m-30f3c8ffd9ca429ab6726a4b317605f7|
10-10 12:59:59|DEBUG:gui:formdoc m-30f3c8ffd9ca429ab6726a4b317605f7

**Comment by HTsybenko** [comment]
Cannot verify the fix due to the existing bug in #107.

**Comment by HTsybenko** [comment]
The unidentified items can be edited via "Sequential edit".
