### ISSUE TITLE
Edit of sample that has no project

### ISSUE THREAD

**Issue by SteffenBrinckmann** [PASTA-ELN/pasta-eln#85]
Traceback (most recent call last):
  File "/home/steffen/FZJ/PASTA/pasta-eln/pasta_eln/gui.py", line 127, in formDoc
    formWindow = Form(self.comm, doc)
  File "/home/steffen/FZJ/PASTA/pasta-eln/pasta_eln/GUI/form.py", line 158, in __init__
    if '-branch' not in self.doc or all(line['id']!=branch['stack'][0] for branch in self.doc['-branch']):
  File "/home/steffen/FZJ/PASTA/pasta-eln/pasta_eln/GUI/form.py", line 158, in <genexpr>
    if '-branch' not in self.doc or all(line['id']!=branch['stack'][0] for branch in self.doc['-branch']):
IndexError: list index out of range

**Comment by HTsybenko** [comment]
This issue seems to be quite similar to the #82 .

**Comment by HTsybenko** [comment]
Cannot verify the fix due to the existing bug in https://github.com/PASTA-ELN/pasta-eln/issues/107.

**Comment by HTsybenko** [comment]
If the issue is the same as #82, the bug was fixed.
