### ISSUE TITLE
Autosaving after adding the comment

### ISSUE THREAD

**Issue by HTsybenko** [PASTA-ELN/pasta-eln#87]
1) Go to the Table view and open an item with a double click to edit.
2) Add a comment and save. For example:
![Screenshot from 2023-10-16 14-17-34](https://github.com/PASTA-ELN/pasta-eln/assets/125445347/94a83739-b448-4735-b814-2fcc8cfcb88f)

3) Wait for some time, I guess to trigger the autosave. 
4) After a while, double clicking again on the item to edit will raise an error:

Traceback (most recent call last):
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/gui.py", line 127, in formDoc
    formWindow = Form(self.comm, doc)
  File "/home/htsybenko/Temp/envir/lib/python3.10/site-packages/pasta_eln/GUI/form.py", line 186, in __init__
    getattr(self, f'key_{key}').setText(content[key])
AttributeError: 'PySide6.QtWidgets.QComboBox' object has no attribute 'setText'. Did you mean: 'itemText'?

10-16 14:07:54|INFO:Start PASTA GUI
10-16 14:07:54|INFO:End PASTA GUI
10-16 14:08:03|INFO:Start PASTA GUI
10-16 14:08:03|INFO:End PASTA GUI
10-16 14:08:05|DEBUG:table:changeTable |measurement|x-3ea9adf1fb2b46d8854a242b087c913b|
10-16 14:08:06|DEBUG:details:changeDetails |m-8ebe57f5e0944445aa69d717ccef0cfd|
10-16 14:08:07|DEBUG:details:changeDetails |m-ba345423016442df9eebe15889128fd6|
10-16 14:08:08|DEBUG:details:changeDetails |m-ba345423016442df9eebe15889128fd6|
10-16 14:08:08|DEBUG:gui:formdoc m-ba345423016442df9eebe15889128fd6
10-16 14:08:21|DEBUG:Add/edit data in cwd:/home/htsybenko/Data/PastasExampleProject/002_DataFiles/simple.png with stack:['x-3ea9adf1fb2b46d8854a242b087c913b', 'x-0532ed433cc145968406791b17de0e00'] and name: simple.png type:['measurement', 'image'] and edit: True
10-16 14:08:21|DEBUG:database.update.3: doc update success: m-ba345423016442df9eebe15889128fd6 simple.png

10-16 14:08:21|DEBUG:table:changeTable |||
10-16 14:08:21|DEBUG:details:changeDetails |redraw|
10-16 14:11:44|DEBUG:details:changeDetails |m-ba345423016442df9eebe15889128fd6|
10-16 14:11:44|DEBUG:details:changeDetails |m-ba345423016442df9eebe15889128fd6|
10-16 14:11:44|DEBUG:gui:formdoc m-ba345423016442df9eebe15889128fd6
10-16 14:13:11|DEBUG:details:changeDetails |m-ba345423016442df9eebe15889128fd6|
10-16 14:13:11|DEBUG:gui:formdoc m-ba345423016442df9eebe15889128fd6
10-16 14:13:11|DEBUG:table:changeTable |||
10-16 14:13:11|DEBUG:details:changeDetails |redraw|
10-16 14:13:11|DEBUG:details:changeDetails |m-ba345423016442df9eebe15889128fd6|

**Comment by HTsybenko** [comment]
The issue is fixed.
